name: hello world

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      # récupère le code de la branche qui a déclenché le workflow
      - uses: actions/checkout@v7
      - run: echo "hello world"
